// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Archive: typeof import('./src/components/archive/index.vue')['default']
    Card: typeof import('./src/components/card/index.vue')['default']
    CardPhoto: typeof import('./src/components/cardPhoto/index.vue')['default']
    Cards: typeof import('./src/components/card/cards.vue')['default']
    ChangeLanguage: typeof import('./src/components/changeLanguage/changeLanguage.vue')['default']
    ChangeTheme: typeof import('./src/components/changeTheme/changeTheme.vue')['default']
    Container: typeof import('./src/components/globalContainer/container.vue')['default']
    Crad: typeof import('./src/components/card/crad.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    Gallery: typeof import('./src/components/cardPhoto/gallery.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InexeS: typeof import('./src/components/map/inexe-s.vue')['default']
    List: typeof import('./src/components/list/index.vue')['default']
    LoadMore: typeof import('./src/components/loadMore/index.vue')['default']
    Main: typeof import('./src/components/globalContainer/main.vue')['default']
    Map: typeof import('./src/components/map/index.vue')['default']
    Mian: typeof import('./src/components/container/mian.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TimeSelection: typeof import('./src/components/timeSelection/timeSelection.vue')['default']
  }
}

export {}
