// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Archive: typeof import('./src/components/archive/index.vue')['default']
    BackTopTop: typeof import('./src/components/backTop/top.vue')['default']
    CardPhoto: typeof import('./src/components/cardPhoto/index.vue')['default']
    ChangeLanguageChangeLanguage: typeof import('./src/components/changeLanguage/changeLanguage.vue')['default']
    ChangeThemeChangeTheme: typeof import('./src/components/changeTheme/changeTheme.vue')['default']
    ComponentsComment: typeof import('./src/components/components/Comment.vue')['default']
    ComponentsCommentEditor: typeof import('./src/components/components/CommentEditor.vue')['default']
    ComponentsCommentLoading: typeof import('./src/components/components/CommentLoading.vue')['default']
    ComponentsCommentNode: typeof import('./src/components/components/CommentNode.vue')['default']
    ComponentsEmojiPickerCategories: typeof import('./src/components/components/EmojiPicker/Categories.vue')['default']
    ComponentsEmojiPickerEmoji: typeof import('./src/components/components/EmojiPicker/Emoji.vue')['default']
    ComponentsEmojiPickerEmojiList: typeof import('./src/components/components/EmojiPicker/EmojiList.vue')['default']
    ComponentsEmojiPickerHelper: typeof import('./src/components/components/EmojiPicker/Helper.vue')['default']
    ComponentsEmojiPickerVEmojiPicker: typeof import('./src/components/components/EmojiPicker/VEmojiPicker.vue')['default']
    ComponentsEmojiPickerVSvg: typeof import('./src/components/components/EmojiPicker/VSvg.vue')['default']
    ComponentsPagination: typeof import('./src/components/components/Pagination.vue')['default']
    ComponentsplComment: typeof import('./src/components/componentspl/Comment.vue')['default']
    ComponentsplCommentEditor: typeof import('./src/components/componentspl/CommentEditor.vue')['default']
    ComponentsplCommentLoading: typeof import('./src/components/componentspl/CommentLoading.vue')['default']
    ComponentsplCommentNode: typeof import('./src/components/componentspl/CommentNode.vue')['default']
    ComponentsplEmojiPickerCategories: typeof import('./src/components/componentspl/EmojiPicker/Categories.vue')['default']
    ComponentsplEmojiPickerEmoji: typeof import('./src/components/componentspl/EmojiPicker/Emoji.vue')['default']
    ComponentsplEmojiPickerEmojiList: typeof import('./src/components/componentspl/EmojiPicker/EmojiList.vue')['default']
    ComponentsplEmojiPickerHelper: typeof import('./src/components/componentspl/EmojiPicker/Helper.vue')['default']
    ComponentsplEmojiPickerVEmojiPicker: typeof import('./src/components/componentspl/EmojiPicker/VEmojiPicker.vue')['default']
    ComponentsplEmojiPickerVSvg: typeof import('./src/components/componentspl/EmojiPicker/VSvg.vue')['default']
    ComponentsplPagination: typeof import('./src/components/componentspl/Pagination.vue')['default']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    GlobalContainerContainer: typeof import('./src/components/globalContainer/container.vue')['default']
    List: typeof import('./src/components/list/index.vue')['default']
    LoadMore: typeof import('./src/components/loadMore/index.vue')['default']
    Map: typeof import('./src/components/map/index.vue')['default']
    MessageIntroduce: typeof import('./src/components/message/introduce.vue')['default']
    MessageJuejin: typeof import('./src/components/message/juejin.vue')['default']
    MessageLink: typeof import('./src/components/message/link.vue')['default']
    MessageWellknown: typeof import('./src/components/message/wellknown.vue')['default']
    MobileArchive: typeof import('./src/components/mobile/archive/index.vue')['default']
    MobileList: typeof import('./src/components/mobile/list/index.vue')['default']
    ReadMobileread: typeof import('./src/components/read/mobileread.vue')['default']
    ReadPcread: typeof import('./src/components/read/pcread.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TimeSelectionTimeSelection: typeof import('./src/components/timeSelection/timeSelection.vue')['default']
  }
}

export {}
