// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Archive: typeof import('./src/components/archive/index.vue')['default']
    CardPhoto: typeof import('./src/components/cardPhoto/index.vue')['default']
    ChangeLanguageChangeLanguage: typeof import('./src/components/changeLanguage/changeLanguage.vue')['default']
    ChangeThemeChangeTheme: typeof import('./src/components/changeTheme/changeTheme.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    GlobalContainerContainer: typeof import('./src/components/globalContainer/container.vue')['default']
    List: typeof import('./src/components/list/index.vue')['default']
    LoadMore: typeof import('./src/components/loadMore/index.vue')['default']
    Map: typeof import('./src/components/map/index.vue')['default']
    MobileArchive: typeof import('./src/components/mobile/archive/index.vue')['default']
    MobileList: typeof import('./src/components/mobile/list/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TimeSelectionTimeSelection: typeof import('./src/components/timeSelection/timeSelection.vue')['default']
  }
}

export {}
